# NUMPY

In [3]:
import numpy
arr=numpy.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [4]:
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [5]:
arr=np.array(45)
print(arr)

45


In [6]:
arr1=np.array([5,6,7,8])
print(arr1)

[5 6 7 8]


In [7]:
arr2=np.array([[1,2],[3,4]])
print(arr2)

[[1 2]
 [3 4]]


In [8]:
arr3=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(arr3)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [9]:
print(arr.ndim)

0


In [10]:
print(arr1.ndim)

1


In [11]:
print(arr2.ndim)

2


In [12]:
print(arr3.ndim)

3
