# NUMPY

In [3]:
import numpy
arr=numpy.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [4]:
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [5]:
arr=np.array(45)
print(arr)

45


In [6]:
arr1=np.array([5,6,7,8])
print(arr1)

[5 6 7 8]


In [7]:
arr2=np.array([[1,2],[3,4]])
print(arr2)

[[1 2]
 [3 4]]


In [8]:
arr3=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(arr3)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [9]:
print(arr.ndim)

0


In [10]:
print(arr1.ndim)

1


In [11]:
print(arr2.ndim)

2


In [12]:
print(arr3.ndim)

3


In [5]:
import numpy as np
arr1=np.array([1,2,3,4,5,6])
print(arr1.reshape(2,3))

[[1 2 3]
 [4 5 6]]


In [6]:
arr1=np.array([1,2,3,4,5,6])
for i in arr1:
    print(i)

1
2
3
4
5
6


In [7]:
for i in np.nditer(arr1):
    print(i)

1
2
3
4
5
6


In [5]:
import numpy as np
arr1=np.array([[1,2,3,4,5,6],[7,8,9,10,11,12],[13,14,15,16,17,18]])
for i in np.nditer(arr1):
    print(i)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18


In [6]:
import numpy as np
arr1=np.array([[1,2,3,4,5,6],[7,8,9,10,11,12],[13,14,15,16,17,18]])
for i,j in np.ndenumerate(arr1):
    print(i,j)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(0, 4) 5
(0, 5) 6
(1, 0) 7
(1, 1) 8
(1, 2) 9
(1, 3) 10
(1, 4) 11
(1, 5) 12
(2, 0) 13
(2, 1) 14
(2, 2) 15
(2, 3) 16
(2, 4) 17
(2, 5) 18


In [10]:
import numpy as np
arr1=np.array([1,2,3,4,5,6])
arr2=np.array([7,8,9,10,11,12])
a=np.concatenate((arr1,arr2))
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [14]:

import numpy as np
arr1=np.array([1,2,3,4,5,6])
arr2=np.array([])
a=np.concatenate((arr1,arr2))
print(a)

[1. 2. 3. 4. 5. 6.]


In [15]:
#WAP CREATE A NUMPY ARRAY WITH 3 DIMENSION OF SHAPE OF 2,2,5 USING RESHAPE FUNCTION
import numpy as np
arr1=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20])
print(arr1.reshape(2,2,5))

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]

 [[11 12 13 14 15]
  [16 17 18 19 20]]]


In [28]:
import numpy as np
class matrix:
    def __init__(self,m):
        self.m=m
    def __add__(self,other):
        return (np.add(self.m,other.m))
    def __mul__(self,other):
        return (np.dot(self.m,other.m))
m1=matrix(np.array([[1,2],[4,5]]))
m2=matrix(np.array([[7,8],[10,11]]))
print(m1+m2)
print(m1*m2)

[[ 8 10]
 [14 16]]
[[27 30]
 [78 87]]


In [33]:
#QB 673
