# NUMPY

In [ ]:
import numpy
arr=numpy.array([1,2,3,4,5])
print(arr)
print(type(arr))

In [ ]:
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr)
print(type(arr))

In [ ]:
arr=np.array(45)
print(arr)

In [ ]:
arr1=np.array([5,6,7,8])
print(arr1)

In [ ]:
arr2=np.array([[1,2],[3,4]])
print(arr2)

In [ ]:
arr3=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(arr3)

In [ ]:
print(arr.ndim)

In [ ]:
print(arr1.ndim)

In [ ]:
print(arr2.ndim)

In [ ]:
print(arr3.ndim)

In [ ]:
import numpy as np
arr1=np.array([1,2,3,4,5,6])
print(arr1.reshape(2,3))

In [ ]:
arr1=np.array([1,2,3,4,5,6])
for i in arr1:
    print(i)

In [ ]:
for i in np.nditer(arr1):
    print(i)

In [ ]:
import numpy as np
arr1=np.array([[1,2,3,4,5,6],[7,8,9,10,11,12],[13,14,15,16,17,18]])
for i in np.nditer(arr1):
    print(i)

In [ ]:
import numpy as np
arr1=np.array([[1,2,3,4,5,6],[7,8,9,10,11,12],[13,14,15,16,17,18]])
for i,j in np.ndenumerate(arr1):
    print(i,j)

In [ ]:
import numpy as np
arr1=np.array([1,2,3,4,5,6])
arr2=np.array([7,8,9,10,11,12])
a=np.concatenate((arr1,arr2))
print(a)

In [ ]:

import numpy as np
arr1=np.array([1,2,3,4,5,6])
arr2=np.array([])
a=np.concatenate((arr1,arr2))
print(a)

In [ ]:
#WAP CREATE A NUMPY ARRAY WITH 3 DIMENSION OF SHAPE OF 2,2,5 USING RESHAPE FUNCTION
import numpy as np
arr1=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20])
print(arr1.reshape(2,2,5))

In [ ]:
import numpy as np
class matrix:
    def __init__(self,m):
        self.m=m
    def __add__(self,other):
        return (np.add(self.m,other.m))
    def __mul__(self,other):
        return (np.dot(self.m,other.m))
m1=matrix(np.array([[1,2],[4,5]]))
m2=matrix(np.array([[7,8],[10,11]]))
print(m1+m2)
print(m1*m2)

In [4]:
import numpy as n
arr = n.array([[1,2], [3,4], [5,6], [7,8], [9,10], [11,12]])
newarr = n.array_split(arr,3)
print(newarr)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


In [ ]:
import numpy as np
a = np.array([1,2,3,4,5,6])
n_a=np.array_split(a,2)
print(n_a)

In [ ]:
import numpy as np
a = np.array([1,2,3,4,5,6])
n_a=np.array_split(a,3)
print(n_a)

In [ ]:
import numpy as np
a = np.array([1,2,3,4,5,6])
n_a=np.array_split(a,4)
print(n_a)

In [ ]:
import numpy as np
a = np.array([1,2,3,4,5,6])
n_a=np.array_split(a,5)
print(n_a)

In [ ]:
import numpy as np
a = np.array([1,2,3,4,5,6])
n_a=np.array_split(a,6)
print(n_a)

In [ ]:
import numpy as np
a = np.array([1,2,3,4,5,6])
n_a=np.array_split(a,7)
print(n_a)

In [11]:
import numpy as np
a = np.array([[1,2],[3,4],[5,6],[7,8]])
n_a=np.array_split(a,1,axis=1)
print(n_a)

[array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])]


In [18]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8])
x=np.where(arr%2==0)
print(x)
print(np.sort(arr))

(array([1, 3, 5, 7], dtype=int64),)
[1 2 3 4 5 6 7 8]


In [19]:
a=np.array([[1,5,3],[6,0,3]])
print(np.sort(a))

[[1 3 5]
 [0 3 6]]


In [ ]:
#find max rows and min from cols  